### ISSUE TITLE
/model/predict doesn't handle invalid input format

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Speech-to-Text-Converter#2]
`/model/predict` returns HTTP code 500 if the input is not a wav file (e.g. a text file)

**Comment by bdwyer2** [comment]
I am unable to reproduce this error locally. We also have a test to check for this and it doesn't seem to be picking this up

https://github.com/IBM/MAX-Speech-to-Text-Converter/blob/master/tests/test.py#L80

**Comment by bdwyer2** [comment]
I am unable to reproduce this error locally. We also have a test to check for this and it doesn't seem to be picking this up

https://github.com/IBM/MAX-Speech-to-Text-Converter/blob/master/tests/test.py#L80

**Comment by ptitzler** [comment]
![image](https://user-images.githubusercontent.com/13068832/55203942-86c67300-518a-11e9-9a44-df9e0446e328.png)
